auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /data/loki
  storage:
    filesystem:
      chunks_directory: /data/loki/chunks
      rules_directory: /data/loki/rules
  ring:
    kvstore:
      store: inmemory
  replication_factor: 1

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  wal:
    dir: "/data/loki/wal"

compactor:
  working_directory: "/data/loki/compactor"

schema_config:
  configs:
    - from: 2025-01-01
      store: tsdb
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /data/loki/index
    cache_location: /data/loki/index_cache
    cache_ttl: 24h
  filesystem:
    directory: /data/loki/chunks

ruler:
  storage:
    type: local
    local:
      directory: /data/loki/rules

limits_config:
  allow_structured_metadata: false
