apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: prisma-migrate
          image: asia-northeast3-docker.pkg.dev/${GCR_PROJECT}/loalife-artifacts/backend-service:latest
          command: ["npx", "prisma", "migrate", "deploy"]
          env:
            - name: DATABASE_URL
              value: "${DATABASE_URL}"
          volumeMounts:
            - name: app-code
              mountPath: /app
      containers:
        - name: backend
          image: asia-northeast3-docker.pkg.dev/${GCR_PROJECT}/loalife-artifacts/backend-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: DATABASE_URL
              value: "${DATABASE_URL}"
