// Code generated by MockGen. DO NOT EDIT.
// Source: ./auction-item.go
//
// Generated by this command:
//
//	mockgen -source=./auction-item.go -package=loadb -self_package=github.com/KubrickCode/loa-work/src/go/libs/loadb
//

// Package loadb is a generated GoMock package.
package loadb

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuctionItemDB is a mock of AuctionItemDB interface.
type MockAuctionItemDB struct {
	ctrl     *gomock.Controller
	recorder *MockAuctionItemDBMockRecorder
	isgomock struct{}
}

// MockAuctionItemDBMockRecorder is the mock recorder for MockAuctionItemDB.
type MockAuctionItemDBMockRecorder struct {
	mock *MockAuctionItemDB
}

// NewMockAuctionItemDB creates a new mock instance.
func NewMockAuctionItemDB(ctrl *gomock.Controller) *MockAuctionItemDB {
	mock := &MockAuctionItemDB{ctrl: ctrl}
	mock.recorder = &MockAuctionItemDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuctionItemDB) EXPECT() *MockAuctionItemDBMockRecorder {
	return m.recorder
}

// FindAllWithRecentStats mocks base method.
func (m *MockAuctionItemDB) FindAllWithRecentStats(take int) ([]AuctionItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllWithRecentStats", take)
	ret0, _ := ret[0].([]AuctionItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllWithRecentStats indicates an expected call of FindAllWithRecentStats.
func (mr *MockAuctionItemDBMockRecorder) FindAllWithRecentStats(take any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllWithRecentStats", reflect.TypeOf((*MockAuctionItemDB)(nil).FindAllWithRecentStats), take)
}

// FindByName mocks base method.
func (m *MockAuctionItemDB) FindByName(name string) (AuctionItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", name)
	ret0, _ := ret[0].(AuctionItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockAuctionItemDBMockRecorder) FindByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockAuctionItemDB)(nil).FindByName), name)
}

// FindStatScraperEnabledAll mocks base method.
func (m *MockAuctionItemDB) FindStatScraperEnabledAll() ([]AuctionItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindStatScraperEnabledAll")
	ret0, _ := ret[0].([]AuctionItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindStatScraperEnabledAll indicates an expected call of FindStatScraperEnabledAll.
func (mr *MockAuctionItemDBMockRecorder) FindStatScraperEnabledAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindStatScraperEnabledAll", reflect.TypeOf((*MockAuctionItemDB)(nil).FindStatScraperEnabledAll))
}

// UpdateStat mocks base method.
func (m *MockAuctionItemDB) UpdateStat(item AuctionItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStat", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStat indicates an expected call of UpdateStat.
func (mr *MockAuctionItemDBMockRecorder) UpdateStat(item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStat", reflect.TypeOf((*MockAuctionItemDB)(nil).UpdateStat), item)
}
