server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loa-work-grafana.duckdns.org:3100/loki/api/v1/push
scrape_configs:
  - job_name: docker
    static_configs:
      - labels:
          job: market-item-stat-scraper
          __path__: /var/lib/docker/containers/*/*-json.log
