version: "3.8"

services:
  postgres:
    image: postgres:13.6-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    command: ["postgres", "-c", "log_statement=all"]
    network_mode: "service:workspace"

  workspace:
    image: mcr.microsoft.com/devcontainers/base:debian
    environment:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
    privileged: true
    volumes:
      - ..:/workspaces/loa-work:delegated
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: "service:workspace"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    network_mode: "service:workspace"
    environment:
      - GF_SERVER_HTTP_PORT=8888

volumes:
  postgres-data:
  grafana-data:
