global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["localhost:3001"]
  - job_name: "auction-item-stat-scraper"
    static_configs:
      - targets: ["localhost:3002"]
  - job_name: "market-item-stat-scraper"
    static_configs:
      - targets: ["localhost:3003"]
