name: Run Tests

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
      - unlocked
  push:
    branches:
      - main

jobs:
  go-tests:
    name: Run Go tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Set up Just CLI
        uses: extractions/setup-just@v1

      - name: Run Go tests
        run: just go-test
