name: Run Tests

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
      - unlocked
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backend-tests:
    name: Run Backend tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node 22
        uses: actions/setup-node@v2
        with:
          node-version: "22.11.0"

      - uses: extractions/setup-just@v1

      - name: Install dependencies
        run: just deps

      - name: Create and start databases
        run: docker compose -f ./infra/docker-compose.ci.yaml up -d

      - name: Wait for database to be ready
        run: |
          npm install -g wait-on
          wait-on tcp:5432

      - name: Run tests
        run: just test backend

  go-tests:
    name: Run Go tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Set up Just CLI
        uses: extractions/setup-just@v1

      - name: Run Go tests
        run: just go-test
