// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ContentCategory is an object representing the database table.
type ContentCategory struct {
	ID        int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	Name      string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	ImageURL  string    `boil:"image_url" json:"image_url" toml:"image_url" yaml:"image_url"`

	R *contentCategoryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L contentCategoryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ContentCategoryColumns = struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	Name      string
	ImageURL  string
}{
	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	Name:      "name",
	ImageURL:  "image_url",
}

var ContentCategoryTableColumns = struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	Name      string
	ImageURL  string
}{
	ID:        "content_category.id",
	CreatedAt: "content_category.created_at",
	UpdatedAt: "content_category.updated_at",
	Name:      "content_category.name",
	ImageURL:  "content_category.image_url",
}

// Generated where

var ContentCategoryWhere = struct {
	ID        whereHelperint
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
	Name      whereHelperstring
	ImageURL  whereHelperstring
}{
	ID:        whereHelperint{field: "\"content_category\".\"id\""},
	CreatedAt: whereHelpertime_Time{field: "\"content_category\".\"created_at\""},
	UpdatedAt: whereHelpertime_Time{field: "\"content_category\".\"updated_at\""},
	Name:      whereHelperstring{field: "\"content_category\".\"name\""},
	ImageURL:  whereHelperstring{field: "\"content_category\".\"image_url\""},
}

// ContentCategoryRels is where relationship names are stored.
var ContentCategoryRels = struct {
	Contents string
}{
	Contents: "Contents",
}

// contentCategoryR is where relationships are stored.
type contentCategoryR struct {
	Contents ContentSlice `boil:"Contents" json:"Contents" toml:"Contents" yaml:"Contents"`
}

// NewStruct creates a new relationship struct
func (*contentCategoryR) NewStruct() *contentCategoryR {
	return &contentCategoryR{}
}

func (o *ContentCategory) GetContents() ContentSlice {
	if o == nil {
		return nil
	}

	return o.R.GetContents()
}

func (r *contentCategoryR) GetContents() ContentSlice {
	if r == nil {
		return nil
	}

	return r.Contents
}

// contentCategoryL is where Load methods for each relationship are stored.
type contentCategoryL struct{}

var (
	contentCategoryAllColumns            = []string{"id", "created_at", "updated_at", "name", "image_url"}
	contentCategoryColumnsWithoutDefault = []string{"updated_at", "name", "image_url"}
	contentCategoryColumnsWithDefault    = []string{"id", "created_at"}
	contentCategoryPrimaryKeyColumns     = []string{"id"}
	contentCategoryGeneratedColumns      = []string{}
)

type (
	// ContentCategorySlice is an alias for a slice of pointers to ContentCategory.
	// This should almost always be used instead of []ContentCategory.
	ContentCategorySlice []*ContentCategory
	// ContentCategoryHook is the signature for custom ContentCategory hook methods
	ContentCategoryHook func(context.Context, boil.ContextExecutor, *ContentCategory) error

	contentCategoryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	contentCategoryType                 = reflect.TypeOf(&ContentCategory{})
	contentCategoryMapping              = queries.MakeStructMapping(contentCategoryType)
	contentCategoryPrimaryKeyMapping, _ = queries.BindMapping(contentCategoryType, contentCategoryMapping, contentCategoryPrimaryKeyColumns)
	contentCategoryInsertCacheMut       sync.RWMutex
	contentCategoryInsertCache          = make(map[string]insertCache)
	contentCategoryUpdateCacheMut       sync.RWMutex
	contentCategoryUpdateCache          = make(map[string]updateCache)
	contentCategoryUpsertCacheMut       sync.RWMutex
	contentCategoryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var contentCategoryAfterSelectMu sync.Mutex
var contentCategoryAfterSelectHooks []ContentCategoryHook

var contentCategoryBeforeInsertMu sync.Mutex
var contentCategoryBeforeInsertHooks []ContentCategoryHook
var contentCategoryAfterInsertMu sync.Mutex
var contentCategoryAfterInsertHooks []ContentCategoryHook

var contentCategoryBeforeUpdateMu sync.Mutex
var contentCategoryBeforeUpdateHooks []ContentCategoryHook
var contentCategoryAfterUpdateMu sync.Mutex
var contentCategoryAfterUpdateHooks []ContentCategoryHook

var contentCategoryBeforeDeleteMu sync.Mutex
var contentCategoryBeforeDeleteHooks []ContentCategoryHook
var contentCategoryAfterDeleteMu sync.Mutex
var contentCategoryAfterDeleteHooks []ContentCategoryHook

var contentCategoryBeforeUpsertMu sync.Mutex
var contentCategoryBeforeUpsertHooks []ContentCategoryHook
var contentCategoryAfterUpsertMu sync.Mutex
var contentCategoryAfterUpsertHooks []ContentCategoryHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ContentCategory) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range contentCategoryAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ContentCategory) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range contentCategoryBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ContentCategory) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range contentCategoryAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ContentCategory) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range contentCategoryBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ContentCategory) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range contentCategoryAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ContentCategory) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range contentCategoryBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ContentCategory) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range contentCategoryAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ContentCategory) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range contentCategoryBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ContentCategory) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range contentCategoryAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddContentCategoryHook registers your hook function for all future operations.
func AddContentCategoryHook(hookPoint boil.HookPoint, contentCategoryHook ContentCategoryHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		contentCategoryAfterSelectMu.Lock()
		contentCategoryAfterSelectHooks = append(contentCategoryAfterSelectHooks, contentCategoryHook)
		contentCategoryAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		contentCategoryBeforeInsertMu.Lock()
		contentCategoryBeforeInsertHooks = append(contentCategoryBeforeInsertHooks, contentCategoryHook)
		contentCategoryBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		contentCategoryAfterInsertMu.Lock()
		contentCategoryAfterInsertHooks = append(contentCategoryAfterInsertHooks, contentCategoryHook)
		contentCategoryAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		contentCategoryBeforeUpdateMu.Lock()
		contentCategoryBeforeUpdateHooks = append(contentCategoryBeforeUpdateHooks, contentCategoryHook)
		contentCategoryBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		contentCategoryAfterUpdateMu.Lock()
		contentCategoryAfterUpdateHooks = append(contentCategoryAfterUpdateHooks, contentCategoryHook)
		contentCategoryAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		contentCategoryBeforeDeleteMu.Lock()
		contentCategoryBeforeDeleteHooks = append(contentCategoryBeforeDeleteHooks, contentCategoryHook)
		contentCategoryBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		contentCategoryAfterDeleteMu.Lock()
		contentCategoryAfterDeleteHooks = append(contentCategoryAfterDeleteHooks, contentCategoryHook)
		contentCategoryAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		contentCategoryBeforeUpsertMu.Lock()
		contentCategoryBeforeUpsertHooks = append(contentCategoryBeforeUpsertHooks, contentCategoryHook)
		contentCategoryBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		contentCategoryAfterUpsertMu.Lock()
		contentCategoryAfterUpsertHooks = append(contentCategoryAfterUpsertHooks, contentCategoryHook)
		contentCategoryAfterUpsertMu.Unlock()
	}
}

// OneG returns a single contentCategory record from the query using the global executor.
func (q contentCategoryQuery) OneG(ctx context.Context) (*ContentCategory, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single contentCategory record from the query.
func (q contentCategoryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ContentCategory, error) {
	o := &ContentCategory{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for content_category")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all ContentCategory records from the query using the global executor.
func (q contentCategoryQuery) AllG(ctx context.Context) (ContentCategorySlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all ContentCategory records from the query.
func (q contentCategoryQuery) All(ctx context.Context, exec boil.ContextExecutor) (ContentCategorySlice, error) {
	var o []*ContentCategory

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ContentCategory slice")
	}

	if len(contentCategoryAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all ContentCategory records in the query using the global executor
func (q contentCategoryQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all ContentCategory records in the query.
func (q contentCategoryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count content_category rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q contentCategoryQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q contentCategoryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if content_category exists")
	}

	return count > 0, nil
}

// Contents retrieves all the content's Contents with an executor.
func (o *ContentCategory) Contents(mods ...qm.QueryMod) contentQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"content\".\"content_category_id\"=?", o.ID),
	)

	return Contents(queryMods...)
}

// LoadContents allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (contentCategoryL) LoadContents(ctx context.Context, e boil.ContextExecutor, singular bool, maybeContentCategory interface{}, mods queries.Applicator) error {
	var slice []*ContentCategory
	var object *ContentCategory

	if singular {
		var ok bool
		object, ok = maybeContentCategory.(*ContentCategory)
		if !ok {
			object = new(ContentCategory)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeContentCategory)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeContentCategory))
			}
		}
	} else {
		s, ok := maybeContentCategory.(*[]*ContentCategory)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeContentCategory)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeContentCategory))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &contentCategoryR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &contentCategoryR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`content`),
		qm.WhereIn(`content.content_category_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load content")
	}

	var resultSlice []*Content
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice content")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on content")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for content")
	}

	if len(contentAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Contents = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &contentR{}
			}
			foreign.R.ContentCategory = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.ContentCategoryID {
				local.R.Contents = append(local.R.Contents, foreign)
				if foreign.R == nil {
					foreign.R = &contentR{}
				}
				foreign.R.ContentCategory = local
				break
			}
		}
	}

	return nil
}

// AddContentsG adds the given related objects to the existing relationships
// of the content_category, optionally inserting them as new records.
// Appends related to o.R.Contents.
// Sets related.R.ContentCategory appropriately.
// Uses the global database handle.
func (o *ContentCategory) AddContentsG(ctx context.Context, insert bool, related ...*Content) error {
	return o.AddContents(ctx, boil.GetContextDB(), insert, related...)
}

// AddContents adds the given related objects to the existing relationships
// of the content_category, optionally inserting them as new records.
// Appends related to o.R.Contents.
// Sets related.R.ContentCategory appropriately.
func (o *ContentCategory) AddContents(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Content) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ContentCategoryID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"content\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"content_category_id"}),
				strmangle.WhereClause("\"", "\"", 2, contentPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ContentCategoryID = o.ID
		}
	}

	if o.R == nil {
		o.R = &contentCategoryR{
			Contents: related,
		}
	} else {
		o.R.Contents = append(o.R.Contents, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &contentR{
				ContentCategory: o,
			}
		} else {
			rel.R.ContentCategory = o
		}
	}
	return nil
}

// ContentCategories retrieves all the records using an executor.
func ContentCategories(mods ...qm.QueryMod) contentCategoryQuery {
	mods = append(mods, qm.From("\"content_category\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"content_category\".*"})
	}

	return contentCategoryQuery{q}
}

// FindContentCategoryG retrieves a single record by ID.
func FindContentCategoryG(ctx context.Context, iD int, selectCols ...string) (*ContentCategory, error) {
	return FindContentCategory(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindContentCategory retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindContentCategory(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*ContentCategory, error) {
	contentCategoryObj := &ContentCategory{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"content_category\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, contentCategoryObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from content_category")
	}

	if err = contentCategoryObj.doAfterSelectHooks(ctx, exec); err != nil {
		return contentCategoryObj, err
	}

	return contentCategoryObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *ContentCategory) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ContentCategory) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no content_category provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(contentCategoryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	contentCategoryInsertCacheMut.RLock()
	cache, cached := contentCategoryInsertCache[key]
	contentCategoryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			contentCategoryAllColumns,
			contentCategoryColumnsWithDefault,
			contentCategoryColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(contentCategoryType, contentCategoryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(contentCategoryType, contentCategoryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"content_category\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"content_category\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into content_category")
	}

	if !cached {
		contentCategoryInsertCacheMut.Lock()
		contentCategoryInsertCache[key] = cache
		contentCategoryInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single ContentCategory record using the global executor.
// See Update for more documentation.
func (o *ContentCategory) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the ContentCategory.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ContentCategory) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	contentCategoryUpdateCacheMut.RLock()
	cache, cached := contentCategoryUpdateCache[key]
	contentCategoryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			contentCategoryAllColumns,
			contentCategoryPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update content_category, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"content_category\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, contentCategoryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(contentCategoryType, contentCategoryMapping, append(wl, contentCategoryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update content_category row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for content_category")
	}

	if !cached {
		contentCategoryUpdateCacheMut.Lock()
		contentCategoryUpdateCache[key] = cache
		contentCategoryUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q contentCategoryQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q contentCategoryQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for content_category")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for content_category")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o ContentCategorySlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ContentCategorySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), contentCategoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"content_category\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, contentCategoryPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in contentCategory slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all contentCategory")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *ContentCategory) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ContentCategory) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no content_category provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(contentCategoryColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	contentCategoryUpsertCacheMut.RLock()
	cache, cached := contentCategoryUpsertCache[key]
	contentCategoryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			contentCategoryAllColumns,
			contentCategoryColumnsWithDefault,
			contentCategoryColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			contentCategoryAllColumns,
			contentCategoryPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert content_category, could not build update column list")
		}

		ret := strmangle.SetComplement(contentCategoryAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(contentCategoryPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert content_category, could not build conflict column list")
			}

			conflict = make([]string, len(contentCategoryPrimaryKeyColumns))
			copy(conflict, contentCategoryPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"content_category\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(contentCategoryType, contentCategoryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(contentCategoryType, contentCategoryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert content_category")
	}

	if !cached {
		contentCategoryUpsertCacheMut.Lock()
		contentCategoryUpsertCache[key] = cache
		contentCategoryUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single ContentCategory record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *ContentCategory) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single ContentCategory record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ContentCategory) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ContentCategory provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), contentCategoryPrimaryKeyMapping)
	sql := "DELETE FROM \"content_category\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from content_category")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for content_category")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q contentCategoryQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q contentCategoryQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no contentCategoryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from content_category")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for content_category")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o ContentCategorySlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ContentCategorySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(contentCategoryBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), contentCategoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"content_category\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, contentCategoryPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from contentCategory slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for content_category")
	}

	if len(contentCategoryAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *ContentCategory) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no ContentCategory provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ContentCategory) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindContentCategory(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ContentCategorySlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty ContentCategorySlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ContentCategorySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ContentCategorySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), contentCategoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"content_category\".* FROM \"content_category\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, contentCategoryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ContentCategorySlice")
	}

	*o = slice

	return nil
}

// ContentCategoryExistsG checks if the ContentCategory row exists.
func ContentCategoryExistsG(ctx context.Context, iD int) (bool, error) {
	return ContentCategoryExists(ctx, boil.GetContextDB(), iD)
}

// ContentCategoryExists checks if the ContentCategory row exists.
func ContentCategoryExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"content_category\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if content_category exists")
	}

	return exists, nil
}

// Exists checks if the ContentCategory row exists.
func (o *ContentCategory) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ContentCategoryExists(ctx, exec, o.ID)
}
