// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// UserContentReward is an object representing the database table.
type UserContentReward struct {
	ID              int           `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt       time.Time     `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt       time.Time     `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	AverageQuantity types.Decimal `boil:"average_quantity" json:"average_quantity" toml:"average_quantity" yaml:"average_quantity"`
	UserID          int           `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	IsSellable      bool          `boil:"is_sellable" json:"is_sellable" toml:"is_sellable" yaml:"is_sellable"`
	ContentID       int           `boil:"content_id" json:"content_id" toml:"content_id" yaml:"content_id"`
	ItemID          int           `boil:"item_id" json:"item_id" toml:"item_id" yaml:"item_id"`

	R *userContentRewardR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userContentRewardL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserContentRewardColumns = struct {
	ID              string
	CreatedAt       string
	UpdatedAt       string
	AverageQuantity string
	UserID          string
	IsSellable      string
	ContentID       string
	ItemID          string
}{
	ID:              "id",
	CreatedAt:       "created_at",
	UpdatedAt:       "updated_at",
	AverageQuantity: "average_quantity",
	UserID:          "user_id",
	IsSellable:      "is_sellable",
	ContentID:       "content_id",
	ItemID:          "item_id",
}

var UserContentRewardTableColumns = struct {
	ID              string
	CreatedAt       string
	UpdatedAt       string
	AverageQuantity string
	UserID          string
	IsSellable      string
	ContentID       string
	ItemID          string
}{
	ID:              "user_content_reward.id",
	CreatedAt:       "user_content_reward.created_at",
	UpdatedAt:       "user_content_reward.updated_at",
	AverageQuantity: "user_content_reward.average_quantity",
	UserID:          "user_content_reward.user_id",
	IsSellable:      "user_content_reward.is_sellable",
	ContentID:       "user_content_reward.content_id",
	ItemID:          "user_content_reward.item_id",
}

// Generated where

var UserContentRewardWhere = struct {
	ID              whereHelperint
	CreatedAt       whereHelpertime_Time
	UpdatedAt       whereHelpertime_Time
	AverageQuantity whereHelpertypes_Decimal
	UserID          whereHelperint
	IsSellable      whereHelperbool
	ContentID       whereHelperint
	ItemID          whereHelperint
}{
	ID:              whereHelperint{field: "\"user_content_reward\".\"id\""},
	CreatedAt:       whereHelpertime_Time{field: "\"user_content_reward\".\"created_at\""},
	UpdatedAt:       whereHelpertime_Time{field: "\"user_content_reward\".\"updated_at\""},
	AverageQuantity: whereHelpertypes_Decimal{field: "\"user_content_reward\".\"average_quantity\""},
	UserID:          whereHelperint{field: "\"user_content_reward\".\"user_id\""},
	IsSellable:      whereHelperbool{field: "\"user_content_reward\".\"is_sellable\""},
	ContentID:       whereHelperint{field: "\"user_content_reward\".\"content_id\""},
	ItemID:          whereHelperint{field: "\"user_content_reward\".\"item_id\""},
}

// UserContentRewardRels is where relationship names are stored.
var UserContentRewardRels = struct {
	Content string
	Item    string
	User    string
}{
	Content: "Content",
	Item:    "Item",
	User:    "User",
}

// userContentRewardR is where relationships are stored.
type userContentRewardR struct {
	Content *Content `boil:"Content" json:"Content" toml:"Content" yaml:"Content"`
	Item    *Item    `boil:"Item" json:"Item" toml:"Item" yaml:"Item"`
	User    *User    `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*userContentRewardR) NewStruct() *userContentRewardR {
	return &userContentRewardR{}
}

func (o *UserContentReward) GetContent() *Content {
	if o == nil {
		return nil
	}

	return o.R.GetContent()
}

func (r *userContentRewardR) GetContent() *Content {
	if r == nil {
		return nil
	}

	return r.Content
}

func (o *UserContentReward) GetItem() *Item {
	if o == nil {
		return nil
	}

	return o.R.GetItem()
}

func (r *userContentRewardR) GetItem() *Item {
	if r == nil {
		return nil
	}

	return r.Item
}

func (o *UserContentReward) GetUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *userContentRewardR) GetUser() *User {
	if r == nil {
		return nil
	}

	return r.User
}

// userContentRewardL is where Load methods for each relationship are stored.
type userContentRewardL struct{}

var (
	userContentRewardAllColumns            = []string{"id", "created_at", "updated_at", "average_quantity", "user_id", "is_sellable", "content_id", "item_id"}
	userContentRewardColumnsWithoutDefault = []string{"updated_at", "user_id", "content_id", "item_id"}
	userContentRewardColumnsWithDefault    = []string{"id", "created_at", "average_quantity", "is_sellable"}
	userContentRewardPrimaryKeyColumns     = []string{"id"}
	userContentRewardGeneratedColumns      = []string{}
)

type (
	// UserContentRewardSlice is an alias for a slice of pointers to UserContentReward.
	// This should almost always be used instead of []UserContentReward.
	UserContentRewardSlice []*UserContentReward
	// UserContentRewardHook is the signature for custom UserContentReward hook methods
	UserContentRewardHook func(context.Context, boil.ContextExecutor, *UserContentReward) error

	userContentRewardQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userContentRewardType                 = reflect.TypeOf(&UserContentReward{})
	userContentRewardMapping              = queries.MakeStructMapping(userContentRewardType)
	userContentRewardPrimaryKeyMapping, _ = queries.BindMapping(userContentRewardType, userContentRewardMapping, userContentRewardPrimaryKeyColumns)
	userContentRewardInsertCacheMut       sync.RWMutex
	userContentRewardInsertCache          = make(map[string]insertCache)
	userContentRewardUpdateCacheMut       sync.RWMutex
	userContentRewardUpdateCache          = make(map[string]updateCache)
	userContentRewardUpsertCacheMut       sync.RWMutex
	userContentRewardUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userContentRewardAfterSelectMu sync.Mutex
var userContentRewardAfterSelectHooks []UserContentRewardHook

var userContentRewardBeforeInsertMu sync.Mutex
var userContentRewardBeforeInsertHooks []UserContentRewardHook
var userContentRewardAfterInsertMu sync.Mutex
var userContentRewardAfterInsertHooks []UserContentRewardHook

var userContentRewardBeforeUpdateMu sync.Mutex
var userContentRewardBeforeUpdateHooks []UserContentRewardHook
var userContentRewardAfterUpdateMu sync.Mutex
var userContentRewardAfterUpdateHooks []UserContentRewardHook

var userContentRewardBeforeDeleteMu sync.Mutex
var userContentRewardBeforeDeleteHooks []UserContentRewardHook
var userContentRewardAfterDeleteMu sync.Mutex
var userContentRewardAfterDeleteHooks []UserContentRewardHook

var userContentRewardBeforeUpsertMu sync.Mutex
var userContentRewardBeforeUpsertHooks []UserContentRewardHook
var userContentRewardAfterUpsertMu sync.Mutex
var userContentRewardAfterUpsertHooks []UserContentRewardHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserContentReward) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userContentRewardAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserContentReward) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userContentRewardBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserContentReward) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userContentRewardAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserContentReward) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userContentRewardBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserContentReward) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userContentRewardAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserContentReward) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userContentRewardBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserContentReward) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userContentRewardAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserContentReward) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userContentRewardBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserContentReward) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userContentRewardAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserContentRewardHook registers your hook function for all future operations.
func AddUserContentRewardHook(hookPoint boil.HookPoint, userContentRewardHook UserContentRewardHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userContentRewardAfterSelectMu.Lock()
		userContentRewardAfterSelectHooks = append(userContentRewardAfterSelectHooks, userContentRewardHook)
		userContentRewardAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		userContentRewardBeforeInsertMu.Lock()
		userContentRewardBeforeInsertHooks = append(userContentRewardBeforeInsertHooks, userContentRewardHook)
		userContentRewardBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		userContentRewardAfterInsertMu.Lock()
		userContentRewardAfterInsertHooks = append(userContentRewardAfterInsertHooks, userContentRewardHook)
		userContentRewardAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		userContentRewardBeforeUpdateMu.Lock()
		userContentRewardBeforeUpdateHooks = append(userContentRewardBeforeUpdateHooks, userContentRewardHook)
		userContentRewardBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		userContentRewardAfterUpdateMu.Lock()
		userContentRewardAfterUpdateHooks = append(userContentRewardAfterUpdateHooks, userContentRewardHook)
		userContentRewardAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		userContentRewardBeforeDeleteMu.Lock()
		userContentRewardBeforeDeleteHooks = append(userContentRewardBeforeDeleteHooks, userContentRewardHook)
		userContentRewardBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		userContentRewardAfterDeleteMu.Lock()
		userContentRewardAfterDeleteHooks = append(userContentRewardAfterDeleteHooks, userContentRewardHook)
		userContentRewardAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		userContentRewardBeforeUpsertMu.Lock()
		userContentRewardBeforeUpsertHooks = append(userContentRewardBeforeUpsertHooks, userContentRewardHook)
		userContentRewardBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		userContentRewardAfterUpsertMu.Lock()
		userContentRewardAfterUpsertHooks = append(userContentRewardAfterUpsertHooks, userContentRewardHook)
		userContentRewardAfterUpsertMu.Unlock()
	}
}

// OneG returns a single userContentReward record from the query using the global executor.
func (q userContentRewardQuery) OneG(ctx context.Context) (*UserContentReward, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single userContentReward record from the query.
func (q userContentRewardQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserContentReward, error) {
	o := &UserContentReward{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for user_content_reward")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all UserContentReward records from the query using the global executor.
func (q userContentRewardQuery) AllG(ctx context.Context) (UserContentRewardSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all UserContentReward records from the query.
func (q userContentRewardQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserContentRewardSlice, error) {
	var o []*UserContentReward

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to UserContentReward slice")
	}

	if len(userContentRewardAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all UserContentReward records in the query using the global executor
func (q userContentRewardQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all UserContentReward records in the query.
func (q userContentRewardQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count user_content_reward rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q userContentRewardQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q userContentRewardQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if user_content_reward exists")
	}

	return count > 0, nil
}

// Content pointed to by the foreign key.
func (o *UserContentReward) Content(mods ...qm.QueryMod) contentQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ContentID),
	}

	queryMods = append(queryMods, mods...)

	return Contents(queryMods...)
}

// Item pointed to by the foreign key.
func (o *UserContentReward) Item(mods ...qm.QueryMod) itemQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ItemID),
	}

	queryMods = append(queryMods, mods...)

	return Items(queryMods...)
}

// User pointed to by the foreign key.
func (o *UserContentReward) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadContent allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userContentRewardL) LoadContent(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserContentReward interface{}, mods queries.Applicator) error {
	var slice []*UserContentReward
	var object *UserContentReward

	if singular {
		var ok bool
		object, ok = maybeUserContentReward.(*UserContentReward)
		if !ok {
			object = new(UserContentReward)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserContentReward)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserContentReward))
			}
		}
	} else {
		s, ok := maybeUserContentReward.(*[]*UserContentReward)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserContentReward)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserContentReward))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &userContentRewardR{}
		}
		args[object.ContentID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userContentRewardR{}
			}

			args[obj.ContentID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`content`),
		qm.WhereIn(`content.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Content")
	}

	var resultSlice []*Content
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Content")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for content")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for content")
	}

	if len(contentAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Content = foreign
		if foreign.R == nil {
			foreign.R = &contentR{}
		}
		foreign.R.UserContentRewards = append(foreign.R.UserContentRewards, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ContentID == foreign.ID {
				local.R.Content = foreign
				if foreign.R == nil {
					foreign.R = &contentR{}
				}
				foreign.R.UserContentRewards = append(foreign.R.UserContentRewards, local)
				break
			}
		}
	}

	return nil
}

// LoadItem allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userContentRewardL) LoadItem(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserContentReward interface{}, mods queries.Applicator) error {
	var slice []*UserContentReward
	var object *UserContentReward

	if singular {
		var ok bool
		object, ok = maybeUserContentReward.(*UserContentReward)
		if !ok {
			object = new(UserContentReward)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserContentReward)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserContentReward))
			}
		}
	} else {
		s, ok := maybeUserContentReward.(*[]*UserContentReward)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserContentReward)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserContentReward))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &userContentRewardR{}
		}
		args[object.ItemID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userContentRewardR{}
			}

			args[obj.ItemID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`item`),
		qm.WhereIn(`item.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Item")
	}

	var resultSlice []*Item
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Item")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for item")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for item")
	}

	if len(itemAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Item = foreign
		if foreign.R == nil {
			foreign.R = &itemR{}
		}
		foreign.R.UserContentRewards = append(foreign.R.UserContentRewards, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ItemID == foreign.ID {
				local.R.Item = foreign
				if foreign.R == nil {
					foreign.R = &itemR{}
				}
				foreign.R.UserContentRewards = append(foreign.R.UserContentRewards, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userContentRewardL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserContentReward interface{}, mods queries.Applicator) error {
	var slice []*UserContentReward
	var object *UserContentReward

	if singular {
		var ok bool
		object, ok = maybeUserContentReward.(*UserContentReward)
		if !ok {
			object = new(UserContentReward)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserContentReward)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserContentReward))
			}
		}
	} else {
		s, ok := maybeUserContentReward.(*[]*UserContentReward)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserContentReward)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserContentReward))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &userContentRewardR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userContentRewardR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`user`),
		qm.WhereIn(`user.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for user")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for user")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UserContentRewards = append(foreign.R.UserContentRewards, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserContentRewards = append(foreign.R.UserContentRewards, local)
				break
			}
		}
	}

	return nil
}

// SetContentG of the userContentReward to the related item.
// Sets o.R.Content to related.
// Adds o to related.R.UserContentRewards.
// Uses the global database handle.
func (o *UserContentReward) SetContentG(ctx context.Context, insert bool, related *Content) error {
	return o.SetContent(ctx, boil.GetContextDB(), insert, related)
}

// SetContent of the userContentReward to the related item.
// Sets o.R.Content to related.
// Adds o to related.R.UserContentRewards.
func (o *UserContentReward) SetContent(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Content) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_content_reward\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"content_id"}),
		strmangle.WhereClause("\"", "\"", 2, userContentRewardPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ContentID = related.ID
	if o.R == nil {
		o.R = &userContentRewardR{
			Content: related,
		}
	} else {
		o.R.Content = related
	}

	if related.R == nil {
		related.R = &contentR{
			UserContentRewards: UserContentRewardSlice{o},
		}
	} else {
		related.R.UserContentRewards = append(related.R.UserContentRewards, o)
	}

	return nil
}

// SetItemG of the userContentReward to the related item.
// Sets o.R.Item to related.
// Adds o to related.R.UserContentRewards.
// Uses the global database handle.
func (o *UserContentReward) SetItemG(ctx context.Context, insert bool, related *Item) error {
	return o.SetItem(ctx, boil.GetContextDB(), insert, related)
}

// SetItem of the userContentReward to the related item.
// Sets o.R.Item to related.
// Adds o to related.R.UserContentRewards.
func (o *UserContentReward) SetItem(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Item) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_content_reward\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"item_id"}),
		strmangle.WhereClause("\"", "\"", 2, userContentRewardPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ItemID = related.ID
	if o.R == nil {
		o.R = &userContentRewardR{
			Item: related,
		}
	} else {
		o.R.Item = related
	}

	if related.R == nil {
		related.R = &itemR{
			UserContentRewards: UserContentRewardSlice{o},
		}
	} else {
		related.R.UserContentRewards = append(related.R.UserContentRewards, o)
	}

	return nil
}

// SetUserG of the userContentReward to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserContentRewards.
// Uses the global database handle.
func (o *UserContentReward) SetUserG(ctx context.Context, insert bool, related *User) error {
	return o.SetUser(ctx, boil.GetContextDB(), insert, related)
}

// SetUser of the userContentReward to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserContentRewards.
func (o *UserContentReward) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_content_reward\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, userContentRewardPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &userContentRewardR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			UserContentRewards: UserContentRewardSlice{o},
		}
	} else {
		related.R.UserContentRewards = append(related.R.UserContentRewards, o)
	}

	return nil
}

// UserContentRewards retrieves all the records using an executor.
func UserContentRewards(mods ...qm.QueryMod) userContentRewardQuery {
	mods = append(mods, qm.From("\"user_content_reward\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"user_content_reward\".*"})
	}

	return userContentRewardQuery{q}
}

// FindUserContentRewardG retrieves a single record by ID.
func FindUserContentRewardG(ctx context.Context, iD int, selectCols ...string) (*UserContentReward, error) {
	return FindUserContentReward(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindUserContentReward retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserContentReward(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*UserContentReward, error) {
	userContentRewardObj := &UserContentReward{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_content_reward\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, userContentRewardObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from user_content_reward")
	}

	if err = userContentRewardObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userContentRewardObj, err
	}

	return userContentRewardObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *UserContentReward) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserContentReward) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no user_content_reward provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userContentRewardColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userContentRewardInsertCacheMut.RLock()
	cache, cached := userContentRewardInsertCache[key]
	userContentRewardInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userContentRewardAllColumns,
			userContentRewardColumnsWithDefault,
			userContentRewardColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userContentRewardType, userContentRewardMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userContentRewardType, userContentRewardMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_content_reward\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_content_reward\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into user_content_reward")
	}

	if !cached {
		userContentRewardInsertCacheMut.Lock()
		userContentRewardInsertCache[key] = cache
		userContentRewardInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single UserContentReward record using the global executor.
// See Update for more documentation.
func (o *UserContentReward) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the UserContentReward.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserContentReward) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userContentRewardUpdateCacheMut.RLock()
	cache, cached := userContentRewardUpdateCache[key]
	userContentRewardUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userContentRewardAllColumns,
			userContentRewardPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update user_content_reward, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_content_reward\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userContentRewardPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userContentRewardType, userContentRewardMapping, append(wl, userContentRewardPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update user_content_reward row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for user_content_reward")
	}

	if !cached {
		userContentRewardUpdateCacheMut.Lock()
		userContentRewardUpdateCache[key] = cache
		userContentRewardUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q userContentRewardQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q userContentRewardQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for user_content_reward")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for user_content_reward")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o UserContentRewardSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserContentRewardSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userContentRewardPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_content_reward\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userContentRewardPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in userContentReward slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all userContentReward")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *UserContentReward) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserContentReward) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no user_content_reward provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userContentRewardColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userContentRewardUpsertCacheMut.RLock()
	cache, cached := userContentRewardUpsertCache[key]
	userContentRewardUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			userContentRewardAllColumns,
			userContentRewardColumnsWithDefault,
			userContentRewardColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			userContentRewardAllColumns,
			userContentRewardPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert user_content_reward, could not build update column list")
		}

		ret := strmangle.SetComplement(userContentRewardAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(userContentRewardPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert user_content_reward, could not build conflict column list")
			}

			conflict = make([]string, len(userContentRewardPrimaryKeyColumns))
			copy(conflict, userContentRewardPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"user_content_reward\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(userContentRewardType, userContentRewardMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userContentRewardType, userContentRewardMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert user_content_reward")
	}

	if !cached {
		userContentRewardUpsertCacheMut.Lock()
		userContentRewardUpsertCache[key] = cache
		userContentRewardUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single UserContentReward record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *UserContentReward) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single UserContentReward record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserContentReward) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no UserContentReward provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userContentRewardPrimaryKeyMapping)
	sql := "DELETE FROM \"user_content_reward\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from user_content_reward")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for user_content_reward")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q userContentRewardQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q userContentRewardQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no userContentRewardQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from user_content_reward")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for user_content_reward")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o UserContentRewardSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserContentRewardSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userContentRewardBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userContentRewardPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_content_reward\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userContentRewardPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from userContentReward slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for user_content_reward")
	}

	if len(userContentRewardAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *UserContentReward) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no UserContentReward provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserContentReward) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserContentReward(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserContentRewardSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty UserContentRewardSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserContentRewardSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserContentRewardSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userContentRewardPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_content_reward\".* FROM \"user_content_reward\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userContentRewardPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in UserContentRewardSlice")
	}

	*o = slice

	return nil
}

// UserContentRewardExistsG checks if the UserContentReward row exists.
func UserContentRewardExistsG(ctx context.Context, iD int) (bool, error) {
	return UserContentRewardExists(ctx, boil.GetContextDB(), iD)
}

// UserContentRewardExists checks if the UserContentReward row exists.
func UserContentRewardExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_content_reward\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if user_content_reward exists")
	}

	return exists, nil
}

// Exists checks if the UserContentReward row exists.
func (o *UserContentReward) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserContentRewardExists(ctx, exec, o.ID)
}
