// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// UserGoldExchangeRate is an object representing the database table.
type UserGoldExchangeRate struct {
	ID         int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt  time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt  time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	KRWAmount  int       `boil:"krw_amount" json:"krw_amount" toml:"krw_amount" yaml:"krw_amount"`
	GoldAmount int       `boil:"gold_amount" json:"gold_amount" toml:"gold_amount" yaml:"gold_amount"`
	UserID     int       `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	IsEdited   bool      `boil:"is_edited" json:"is_edited" toml:"is_edited" yaml:"is_edited"`

	R *userGoldExchangeRateR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userGoldExchangeRateL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserGoldExchangeRateColumns = struct {
	ID         string
	CreatedAt  string
	UpdatedAt  string
	KRWAmount  string
	GoldAmount string
	UserID     string
	IsEdited   string
}{
	ID:         "id",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
	KRWAmount:  "krw_amount",
	GoldAmount: "gold_amount",
	UserID:     "user_id",
	IsEdited:   "is_edited",
}

var UserGoldExchangeRateTableColumns = struct {
	ID         string
	CreatedAt  string
	UpdatedAt  string
	KRWAmount  string
	GoldAmount string
	UserID     string
	IsEdited   string
}{
	ID:         "user_gold_exchange_rate.id",
	CreatedAt:  "user_gold_exchange_rate.created_at",
	UpdatedAt:  "user_gold_exchange_rate.updated_at",
	KRWAmount:  "user_gold_exchange_rate.krw_amount",
	GoldAmount: "user_gold_exchange_rate.gold_amount",
	UserID:     "user_gold_exchange_rate.user_id",
	IsEdited:   "user_gold_exchange_rate.is_edited",
}

// Generated where

var UserGoldExchangeRateWhere = struct {
	ID         whereHelperint
	CreatedAt  whereHelpertime_Time
	UpdatedAt  whereHelpertime_Time
	KRWAmount  whereHelperint
	GoldAmount whereHelperint
	UserID     whereHelperint
	IsEdited   whereHelperbool
}{
	ID:         whereHelperint{field: "\"user_gold_exchange_rate\".\"id\""},
	CreatedAt:  whereHelpertime_Time{field: "\"user_gold_exchange_rate\".\"created_at\""},
	UpdatedAt:  whereHelpertime_Time{field: "\"user_gold_exchange_rate\".\"updated_at\""},
	KRWAmount:  whereHelperint{field: "\"user_gold_exchange_rate\".\"krw_amount\""},
	GoldAmount: whereHelperint{field: "\"user_gold_exchange_rate\".\"gold_amount\""},
	UserID:     whereHelperint{field: "\"user_gold_exchange_rate\".\"user_id\""},
	IsEdited:   whereHelperbool{field: "\"user_gold_exchange_rate\".\"is_edited\""},
}

// UserGoldExchangeRateRels is where relationship names are stored.
var UserGoldExchangeRateRels = struct {
	User string
}{
	User: "User",
}

// userGoldExchangeRateR is where relationships are stored.
type userGoldExchangeRateR struct {
	User *User `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*userGoldExchangeRateR) NewStruct() *userGoldExchangeRateR {
	return &userGoldExchangeRateR{}
}

func (o *UserGoldExchangeRate) GetUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *userGoldExchangeRateR) GetUser() *User {
	if r == nil {
		return nil
	}

	return r.User
}

// userGoldExchangeRateL is where Load methods for each relationship are stored.
type userGoldExchangeRateL struct{}

var (
	userGoldExchangeRateAllColumns            = []string{"id", "created_at", "updated_at", "krw_amount", "gold_amount", "user_id", "is_edited"}
	userGoldExchangeRateColumnsWithoutDefault = []string{"updated_at", "krw_amount", "gold_amount", "user_id"}
	userGoldExchangeRateColumnsWithDefault    = []string{"id", "created_at", "is_edited"}
	userGoldExchangeRatePrimaryKeyColumns     = []string{"id"}
	userGoldExchangeRateGeneratedColumns      = []string{}
)

type (
	// UserGoldExchangeRateSlice is an alias for a slice of pointers to UserGoldExchangeRate.
	// This should almost always be used instead of []UserGoldExchangeRate.
	UserGoldExchangeRateSlice []*UserGoldExchangeRate
	// UserGoldExchangeRateHook is the signature for custom UserGoldExchangeRate hook methods
	UserGoldExchangeRateHook func(context.Context, boil.ContextExecutor, *UserGoldExchangeRate) error

	userGoldExchangeRateQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userGoldExchangeRateType                 = reflect.TypeOf(&UserGoldExchangeRate{})
	userGoldExchangeRateMapping              = queries.MakeStructMapping(userGoldExchangeRateType)
	userGoldExchangeRatePrimaryKeyMapping, _ = queries.BindMapping(userGoldExchangeRateType, userGoldExchangeRateMapping, userGoldExchangeRatePrimaryKeyColumns)
	userGoldExchangeRateInsertCacheMut       sync.RWMutex
	userGoldExchangeRateInsertCache          = make(map[string]insertCache)
	userGoldExchangeRateUpdateCacheMut       sync.RWMutex
	userGoldExchangeRateUpdateCache          = make(map[string]updateCache)
	userGoldExchangeRateUpsertCacheMut       sync.RWMutex
	userGoldExchangeRateUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userGoldExchangeRateAfterSelectMu sync.Mutex
var userGoldExchangeRateAfterSelectHooks []UserGoldExchangeRateHook

var userGoldExchangeRateBeforeInsertMu sync.Mutex
var userGoldExchangeRateBeforeInsertHooks []UserGoldExchangeRateHook
var userGoldExchangeRateAfterInsertMu sync.Mutex
var userGoldExchangeRateAfterInsertHooks []UserGoldExchangeRateHook

var userGoldExchangeRateBeforeUpdateMu sync.Mutex
var userGoldExchangeRateBeforeUpdateHooks []UserGoldExchangeRateHook
var userGoldExchangeRateAfterUpdateMu sync.Mutex
var userGoldExchangeRateAfterUpdateHooks []UserGoldExchangeRateHook

var userGoldExchangeRateBeforeDeleteMu sync.Mutex
var userGoldExchangeRateBeforeDeleteHooks []UserGoldExchangeRateHook
var userGoldExchangeRateAfterDeleteMu sync.Mutex
var userGoldExchangeRateAfterDeleteHooks []UserGoldExchangeRateHook

var userGoldExchangeRateBeforeUpsertMu sync.Mutex
var userGoldExchangeRateBeforeUpsertHooks []UserGoldExchangeRateHook
var userGoldExchangeRateAfterUpsertMu sync.Mutex
var userGoldExchangeRateAfterUpsertHooks []UserGoldExchangeRateHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserGoldExchangeRate) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userGoldExchangeRateAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserGoldExchangeRate) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userGoldExchangeRateBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserGoldExchangeRate) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userGoldExchangeRateAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserGoldExchangeRate) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userGoldExchangeRateBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserGoldExchangeRate) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userGoldExchangeRateAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserGoldExchangeRate) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userGoldExchangeRateBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserGoldExchangeRate) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userGoldExchangeRateAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserGoldExchangeRate) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userGoldExchangeRateBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserGoldExchangeRate) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userGoldExchangeRateAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserGoldExchangeRateHook registers your hook function for all future operations.
func AddUserGoldExchangeRateHook(hookPoint boil.HookPoint, userGoldExchangeRateHook UserGoldExchangeRateHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userGoldExchangeRateAfterSelectMu.Lock()
		userGoldExchangeRateAfterSelectHooks = append(userGoldExchangeRateAfterSelectHooks, userGoldExchangeRateHook)
		userGoldExchangeRateAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		userGoldExchangeRateBeforeInsertMu.Lock()
		userGoldExchangeRateBeforeInsertHooks = append(userGoldExchangeRateBeforeInsertHooks, userGoldExchangeRateHook)
		userGoldExchangeRateBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		userGoldExchangeRateAfterInsertMu.Lock()
		userGoldExchangeRateAfterInsertHooks = append(userGoldExchangeRateAfterInsertHooks, userGoldExchangeRateHook)
		userGoldExchangeRateAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		userGoldExchangeRateBeforeUpdateMu.Lock()
		userGoldExchangeRateBeforeUpdateHooks = append(userGoldExchangeRateBeforeUpdateHooks, userGoldExchangeRateHook)
		userGoldExchangeRateBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		userGoldExchangeRateAfterUpdateMu.Lock()
		userGoldExchangeRateAfterUpdateHooks = append(userGoldExchangeRateAfterUpdateHooks, userGoldExchangeRateHook)
		userGoldExchangeRateAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		userGoldExchangeRateBeforeDeleteMu.Lock()
		userGoldExchangeRateBeforeDeleteHooks = append(userGoldExchangeRateBeforeDeleteHooks, userGoldExchangeRateHook)
		userGoldExchangeRateBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		userGoldExchangeRateAfterDeleteMu.Lock()
		userGoldExchangeRateAfterDeleteHooks = append(userGoldExchangeRateAfterDeleteHooks, userGoldExchangeRateHook)
		userGoldExchangeRateAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		userGoldExchangeRateBeforeUpsertMu.Lock()
		userGoldExchangeRateBeforeUpsertHooks = append(userGoldExchangeRateBeforeUpsertHooks, userGoldExchangeRateHook)
		userGoldExchangeRateBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		userGoldExchangeRateAfterUpsertMu.Lock()
		userGoldExchangeRateAfterUpsertHooks = append(userGoldExchangeRateAfterUpsertHooks, userGoldExchangeRateHook)
		userGoldExchangeRateAfterUpsertMu.Unlock()
	}
}

// OneG returns a single userGoldExchangeRate record from the query using the global executor.
func (q userGoldExchangeRateQuery) OneG(ctx context.Context) (*UserGoldExchangeRate, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single userGoldExchangeRate record from the query.
func (q userGoldExchangeRateQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserGoldExchangeRate, error) {
	o := &UserGoldExchangeRate{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for user_gold_exchange_rate")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all UserGoldExchangeRate records from the query using the global executor.
func (q userGoldExchangeRateQuery) AllG(ctx context.Context) (UserGoldExchangeRateSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all UserGoldExchangeRate records from the query.
func (q userGoldExchangeRateQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserGoldExchangeRateSlice, error) {
	var o []*UserGoldExchangeRate

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to UserGoldExchangeRate slice")
	}

	if len(userGoldExchangeRateAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all UserGoldExchangeRate records in the query using the global executor
func (q userGoldExchangeRateQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all UserGoldExchangeRate records in the query.
func (q userGoldExchangeRateQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count user_gold_exchange_rate rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q userGoldExchangeRateQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q userGoldExchangeRateQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if user_gold_exchange_rate exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *UserGoldExchangeRate) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userGoldExchangeRateL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserGoldExchangeRate interface{}, mods queries.Applicator) error {
	var slice []*UserGoldExchangeRate
	var object *UserGoldExchangeRate

	if singular {
		var ok bool
		object, ok = maybeUserGoldExchangeRate.(*UserGoldExchangeRate)
		if !ok {
			object = new(UserGoldExchangeRate)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserGoldExchangeRate)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserGoldExchangeRate))
			}
		}
	} else {
		s, ok := maybeUserGoldExchangeRate.(*[]*UserGoldExchangeRate)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserGoldExchangeRate)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserGoldExchangeRate))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &userGoldExchangeRateR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userGoldExchangeRateR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`user`),
		qm.WhereIn(`user.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for user")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for user")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UserGoldExchangeRate = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserGoldExchangeRate = local
				break
			}
		}
	}

	return nil
}

// SetUserG of the userGoldExchangeRate to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserGoldExchangeRate.
// Uses the global database handle.
func (o *UserGoldExchangeRate) SetUserG(ctx context.Context, insert bool, related *User) error {
	return o.SetUser(ctx, boil.GetContextDB(), insert, related)
}

// SetUser of the userGoldExchangeRate to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserGoldExchangeRate.
func (o *UserGoldExchangeRate) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_gold_exchange_rate\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, userGoldExchangeRatePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &userGoldExchangeRateR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			UserGoldExchangeRate: o,
		}
	} else {
		related.R.UserGoldExchangeRate = o
	}

	return nil
}

// UserGoldExchangeRates retrieves all the records using an executor.
func UserGoldExchangeRates(mods ...qm.QueryMod) userGoldExchangeRateQuery {
	mods = append(mods, qm.From("\"user_gold_exchange_rate\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"user_gold_exchange_rate\".*"})
	}

	return userGoldExchangeRateQuery{q}
}

// FindUserGoldExchangeRateG retrieves a single record by ID.
func FindUserGoldExchangeRateG(ctx context.Context, iD int, selectCols ...string) (*UserGoldExchangeRate, error) {
	return FindUserGoldExchangeRate(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindUserGoldExchangeRate retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserGoldExchangeRate(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*UserGoldExchangeRate, error) {
	userGoldExchangeRateObj := &UserGoldExchangeRate{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_gold_exchange_rate\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, userGoldExchangeRateObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from user_gold_exchange_rate")
	}

	if err = userGoldExchangeRateObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userGoldExchangeRateObj, err
	}

	return userGoldExchangeRateObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *UserGoldExchangeRate) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserGoldExchangeRate) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no user_gold_exchange_rate provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userGoldExchangeRateColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userGoldExchangeRateInsertCacheMut.RLock()
	cache, cached := userGoldExchangeRateInsertCache[key]
	userGoldExchangeRateInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userGoldExchangeRateAllColumns,
			userGoldExchangeRateColumnsWithDefault,
			userGoldExchangeRateColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userGoldExchangeRateType, userGoldExchangeRateMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userGoldExchangeRateType, userGoldExchangeRateMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_gold_exchange_rate\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_gold_exchange_rate\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into user_gold_exchange_rate")
	}

	if !cached {
		userGoldExchangeRateInsertCacheMut.Lock()
		userGoldExchangeRateInsertCache[key] = cache
		userGoldExchangeRateInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single UserGoldExchangeRate record using the global executor.
// See Update for more documentation.
func (o *UserGoldExchangeRate) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the UserGoldExchangeRate.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserGoldExchangeRate) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userGoldExchangeRateUpdateCacheMut.RLock()
	cache, cached := userGoldExchangeRateUpdateCache[key]
	userGoldExchangeRateUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userGoldExchangeRateAllColumns,
			userGoldExchangeRatePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update user_gold_exchange_rate, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_gold_exchange_rate\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userGoldExchangeRatePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userGoldExchangeRateType, userGoldExchangeRateMapping, append(wl, userGoldExchangeRatePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update user_gold_exchange_rate row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for user_gold_exchange_rate")
	}

	if !cached {
		userGoldExchangeRateUpdateCacheMut.Lock()
		userGoldExchangeRateUpdateCache[key] = cache
		userGoldExchangeRateUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q userGoldExchangeRateQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q userGoldExchangeRateQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for user_gold_exchange_rate")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for user_gold_exchange_rate")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o UserGoldExchangeRateSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserGoldExchangeRateSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userGoldExchangeRatePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_gold_exchange_rate\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userGoldExchangeRatePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in userGoldExchangeRate slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all userGoldExchangeRate")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *UserGoldExchangeRate) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserGoldExchangeRate) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no user_gold_exchange_rate provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userGoldExchangeRateColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userGoldExchangeRateUpsertCacheMut.RLock()
	cache, cached := userGoldExchangeRateUpsertCache[key]
	userGoldExchangeRateUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			userGoldExchangeRateAllColumns,
			userGoldExchangeRateColumnsWithDefault,
			userGoldExchangeRateColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			userGoldExchangeRateAllColumns,
			userGoldExchangeRatePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert user_gold_exchange_rate, could not build update column list")
		}

		ret := strmangle.SetComplement(userGoldExchangeRateAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(userGoldExchangeRatePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert user_gold_exchange_rate, could not build conflict column list")
			}

			conflict = make([]string, len(userGoldExchangeRatePrimaryKeyColumns))
			copy(conflict, userGoldExchangeRatePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"user_gold_exchange_rate\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(userGoldExchangeRateType, userGoldExchangeRateMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userGoldExchangeRateType, userGoldExchangeRateMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert user_gold_exchange_rate")
	}

	if !cached {
		userGoldExchangeRateUpsertCacheMut.Lock()
		userGoldExchangeRateUpsertCache[key] = cache
		userGoldExchangeRateUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single UserGoldExchangeRate record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *UserGoldExchangeRate) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single UserGoldExchangeRate record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserGoldExchangeRate) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no UserGoldExchangeRate provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userGoldExchangeRatePrimaryKeyMapping)
	sql := "DELETE FROM \"user_gold_exchange_rate\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from user_gold_exchange_rate")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for user_gold_exchange_rate")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q userGoldExchangeRateQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q userGoldExchangeRateQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no userGoldExchangeRateQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from user_gold_exchange_rate")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for user_gold_exchange_rate")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o UserGoldExchangeRateSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserGoldExchangeRateSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userGoldExchangeRateBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userGoldExchangeRatePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_gold_exchange_rate\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userGoldExchangeRatePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from userGoldExchangeRate slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for user_gold_exchange_rate")
	}

	if len(userGoldExchangeRateAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *UserGoldExchangeRate) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no UserGoldExchangeRate provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserGoldExchangeRate) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserGoldExchangeRate(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserGoldExchangeRateSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty UserGoldExchangeRateSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserGoldExchangeRateSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserGoldExchangeRateSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userGoldExchangeRatePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_gold_exchange_rate\".* FROM \"user_gold_exchange_rate\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userGoldExchangeRatePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in UserGoldExchangeRateSlice")
	}

	*o = slice

	return nil
}

// UserGoldExchangeRateExistsG checks if the UserGoldExchangeRate row exists.
func UserGoldExchangeRateExistsG(ctx context.Context, iD int) (bool, error) {
	return UserGoldExchangeRateExists(ctx, boil.GetContextDB(), iD)
}

// UserGoldExchangeRateExists checks if the UserGoldExchangeRate row exists.
func UserGoldExchangeRateExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_gold_exchange_rate\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if user_gold_exchange_rate exists")
	}

	return exists, nil
}

// Exists checks if the UserGoldExchangeRate row exists.
func (o *UserGoldExchangeRate) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserGoldExchangeRateExists(ctx, exec, o.ID)
}
